name: Issue
on:
  issues:
    types: [opened, edited, closed]
jobs:
  New-Issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print issue details
        run: |
          echo "Event Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue User: ${{ github.event.issue.user.login }}"
          echo "Issue Labels: ${{ github.event.issue.labels }}"
          echo "Issue Assignees: ${{ github.event.issue.assignees }}"
          echo "----------------------------------------------------"
          echo "${{ toJSON(github.event) }}"
